In [1]:
print("Hello World")
print('hello world from Python')

Hello World
hello world from Python


In [1]:
x = 5
y = 36.3
z = "hey good morning"
print(x,y,z)

5 36.3 hey good morning


# Python Programming

- Python Data Types & Operators
    - Primitive Data types: int, string, float, boolean, complex
    - Non primitive data types: list, set, tuple, dictionary
    - Operators in python


- Python control flow
    - if else
    - for loop
    - while loop


- Python functions
    - Builtin functions
    - User defined functions

## Python Data types
### Primitive Data types: atomic data types

In [4]:
# I am a single line comment in python

In [2]:
# integer
w = 45
print(w)
type(w)

45


int

In [3]:
# float
m = 4.5
type(m)

float

In [5]:
# string
s = "hi from python"
k = 'hello from python'
print(s,k)
type(s)

hi from python hello from python


str

In [6]:
type(k)

str

In [7]:
# multi line string
w = """ Hi i am part of multiple line string
hey me too part of the same multiple line string
thanks
"""
print(w)

 Hi i am part of multiple line string
hey me too part of the same multiple line string
thanks



In [8]:
type(w)

str

In [9]:
m = True # boolean
print(m)
type(m)

True


bool

In [10]:
# complex
w = 5 + 4j
print(w)

(5+4j)


In [11]:
type(w)

complex

In [16]:
w = 45
print(w)
type(w)

45


int

In [15]:
w = 12
print(type(w)
print(w)

<class 'int'>
12


## Non primitive data types
### List
- used to store a collection of values/objects/elements, it supports repeatation of values as well
- List also accommodate objects/elements of different data types
- List is a mutable object: modifiable object
- A list in python can be created using square/upper bracket: []

In [17]:
x = [45,10.5,'hii','hello',True,2000]
print(x)
type(x)

[45, 10.5, 'hii', 'hello', True, 2000]


list

In [18]:
# check the total number of values in a list
len(x)

6

In [19]:
# indexing: Accessing a single value from the list
# indexing by default starts from 0: left to right
print(x[0])
print(x[3])

45
hello


In [20]:
# python also supports negative indexing: rigt to left, starts from -1
print(x[-1])
print(x[-4])

2000
hii


In [21]:
# slicing: accessing multiple values as another list, lowerbound is included, upperbound excluded
print(x)

[45, 10.5, 'hii', 'hello', True, 2000]


In [22]:
print(x[1:3]) #lowerbound = 1, upperbound = 3

[10.5, 'hii']


In [23]:
print(x[0:3])

[45, 10.5, 'hii']


In [24]:
print(x)

[45, 10.5, 'hii', 'hello', True, 2000]


In [25]:
x.index(True)

4

In [26]:
print(x)

[45, 10.5, 'hii', 'hello', True, 2000]


In [27]:
x[0] = 500 # replacing an existing value in a list by another value
print(x)

[500, 10.5, 'hii', 'hello', True, 2000]


In [28]:
# insert a new object/value in a list at the end of the list
x.append(False)
print(x)

[500, 10.5, 'hii', 'hello', True, 2000, False]


In [29]:
# insert a new object/value in between
x.insert(2,"python")
print(x)

[500, 10.5, 'python', 'hii', 'hello', True, 2000, False]


In [30]:
# remove a value
x.remove(True)
print(x)

[500, 10.5, 'python', 'hii', 'hello', 2000, False]


In [31]:
# remove a value by position
x.pop(3)
print(x)

[500, 10.5, 'python', 'hello', 2000, False]


In [32]:
m = 45
print(m)

45


In [33]:
m = 'hii'
print(m)

hii


### Non primtive data type: Tuple

- used to store a collection of values/objects/elements, it supports repeatation of values as well
- Tuple also accommodate objects/elements of different data types
- Tuple is an immutable object: NOT modifiable
- A tuple in python can be created using round/lower bracket / parenthesis : ()

In [34]:
y = (45,20,'good morning',False)
print(y)
type(y)

(45, 20, 'good morning', False)


tuple

In [35]:
len(y)

4

In [36]:
# indexing
print(y[0])
print(y[2])
print(y[-2])

45
good morning
good morning


In [38]:
# slicing 
print(y[2:5])

('good morning', False)


In [39]:
print(y)

(45, 20, 'good morning', False)


In [40]:
# we can not modify a tuple
y[0] = 50 # this will throw error, as tuples are immutable

TypeError: 'tuple' object does not support item assignment

### Non primitive: Dictionary
- used to store a collection of key:value pairs
- keys has to be unique, immutable, values can be anything
- Dictionary is a mutable object: modifiable
- can be created using curly/middle/flower brackets : {}

In [41]:
w = {"name":"Anshu",'Age':45,'Language':'Python'}
print(w)
type(w)

{'name': 'Anshu', 'Age': 45, 'Language': 'Python'}


dict

In [42]:
len(w)

3

In [43]:
# indexing: fetch value by referring to key
print(w['Age'])

45


In [44]:
# modify
w['name'] = "Anny"
print(w)

{'name': 'Anny', 'Age': 45, 'Language': 'Python'}


In [45]:
w['gender'] = 'male'
print(w)

{'name': 'Anny', 'Age': 45, 'Language': 'Python', 'gender': 'male'}


In [46]:
# remove a key value pair
w.pop("Language")
print(w)

{'name': 'Anny', 'Age': 45, 'gender': 'male'}


In [47]:
data = {'name':['Anshu','Anthony','Ahamad','Ali'],'age':[45,32,25,22]}
print(data)

{'name': ['Anshu', 'Anthony', 'Ahamad', 'Ali'], 'age': [45, 32, 25, 22]}


In [48]:
print(data['name'])

['Anshu', 'Anthony', 'Ahamad', 'Ali']


In [50]:
print(data['name'][0],data['age'][0])

Anshu 45


### Non primitive data type: set
- used to store a  collection of values, does not support repeatation of values
- accommodates objects/values of different data types
- set is a mutable object: modifiable
- an unordered data type: we can not do indexing, the position of values does not matter
- primarily used for set theory operations such as union, intersection
- can be created using curly/middle/flower brackets : {}

In [51]:
a = {4,5,4,5,4,5,4,5,4,5,6,3,2,5,6,9,8}
print(a)

{2, 3, 4, 5, 6, 8, 9}


In [52]:
type(a)

set

In [53]:
b = {1,5,9,8,4,2,7}
print(b)
type(b)

{1, 2, 4, 5, 7, 8, 9}


set

In [54]:
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [55]:
a.intersection(b)

{2, 4, 5, 8, 9}

In [56]:
print(a)
a.remove(5)
print(a)

{2, 3, 4, 5, 6, 8, 9}
{2, 3, 4, 6, 8, 9}


In [57]:
a.add(10)
print(a)

{2, 3, 4, 6, 8, 9, 10}


In [58]:
# list
m = [4,6,5,2,3,6,5]
m.count(5)

2

## Python operators
### Arithmetic Operators

In [59]:
a = 5
b = 6
# addition
print(a+b)

# subtraction
print(a-b)

# Multiplication
print(a*b)

# Division
print(a/b)

# Exponent
print(a**3)

11
-1
30
0.8333333333333334
125


In [61]:
# logical operator
a = True
b = False
print(a and b) # and represents AND logic

False


In [62]:
a or b # or represents OR logic

True

In [63]:
not a 

False

In [64]:
# membership operator
# in, not in 
m = "Hello  from python"
'py' in m

True

In [65]:
'python' not in m

False

In [66]:
k = [4,5,6,3,2]
3 in k

True

In [67]:
9 not in k

True

In [68]:
x = 3
x+=2  # x = x+2
print(x)

5


# Python functions

In [69]:
m = [4,5,3]
print(m)

[4, 5, 3]


In [70]:
type(m)

list

In [71]:
len(m)

3

In [72]:
sum(m)

12

In [73]:
min(m)

3

In [74]:
max(m)

5

In [75]:
sorted(m)

[3, 4, 5]

In [88]:
m = [4,2,5,9,3]
sorted(m,reverse=True)

[9, 5, 4, 3, 2]

In [89]:
m = [4,2,5,9,3]
sum(m) / len(m)

4.6

In [76]:
round(2.25444,2)

2.25

#### Type conversion functions

In [79]:
m = "12.5"
k = float(m) # float() can be used to convert anything to float
print(k,type(k))

12.5 <class 'float'>


In [81]:
m = 12.5
w = int(m)
print(w,type(w))

12 <class 'int'>


In [82]:
m = "45"
w = int(m)
print(w,type(w))

45 <class 'int'>


In [83]:
m = True
k = str(m)
print(k,type(k))

True <class 'str'>


In [84]:
q = 0
g = bool(q)
print(q,type(q))

0 <class 'int'>


In [85]:
m = [4,5,3]
k = tuple(m)
print(k,type(k))

(4, 5, 3) <class 'tuple'>


In [86]:
w = set(m)
print(w,type(w))

{3, 4, 5} <class 'set'>


In [87]:
j = {4,5,3}
m = list(j)
print(m,type(m))

[3, 4, 5] <class 'list'>


### Input function
    - always takes user input as a string

In [90]:
# task: write python code to ask user enter two numbers and display the output
a = input("Enter the first number ")
b = input("Enter the second number ")
c = a + b 
print(c)

68


In [91]:
"Hello " + "world"

'Hello world'

In [96]:
# task: write python code to ask user enter two numbers and display the output
a = input("Enter the first number ")
b = input("Enter the second number ")
c = int(a) + int(b) 
print(c)

11


### Exercise
You need to write python code to create a BMI Calculator
your code should ask user:
1. Enter your weight in KG
2. Enter your height in CMs

your should convert the user height from CM to meters

- Use below formula to compute user bmi (use height in meteres here)

(Perform appropriate type conversion before any calculation)

bmi  = w/(h*h)

your code should print the user bmi

*********************************************

test samples
    w = 60, h = 150, bmi = 26.66666

In [97]:
w = int(input("Enter the weight in KG "))
h = int(input("Enter the height in CMs "))/100 
bmi = w/(h**2)
print("your bmi is ",bmi)

print("your bmi is ",round(bmi,2))

your bmi is  26.666666666666668
your bmi is  26.67


In [98]:
# f string
name = "anshu"
m =f"Hey hi {name} how are you doing, your bmi is {bmi} which is equal to approx {bmi:.2f}"
print(m)  


Hey hi anshu how are you doing, your bmi is 26.666666666666668 which is equal to approx 26.67


In [99]:
print(f"Hey hi {name} how are you doing, your bmi is {bmi} which is equal to approx {bmi:.2f}")

Hey hi anshu how are you doing, your bmi is 26.666666666666668 which is equal to approx 26.67


In [100]:
m ="Hey hi {name} how are you doing, your bmi is {bmi} which is equal to approx {bmi:.2f}"
print(m)  


Hey hi {name} how are you doing, your bmi is {bmi} which is equal to approx {bmi:.2f}


### Python Control Flow

In [101]:
w = int(input("Enter the weight in KG "))
h = int(input("Enter the height in CMs "))/100 
bmi = w/(h**2)
print("your bmi is ",bmi)

your bmi is  26.666666666666668


In [103]:
w = int(input("Enter the weight in KG "))
h = int(input("Enter the height in CMs "))/100 
bmi = w/(h**2)
print("your bmi is ",bmi)

if bmi<25:
    print("your bmi is low")
    print("you need to eat more, walk less, get more healthy")

your bmi is  19.531249999999996
your bmi is low
you need to eat more, walk less, get more healthy


In [104]:
w = int(input("Enter the weight in KG "))
h = int(input("Enter the height in CMs "))/100 
bmi = w/(h**2)
print("your bmi is ",bmi)

if bmi<25:
    print("your bmi is low")
    print("you need to eat more, walk less, get more healthy")
elif bmi>=25 and bmi<30:
    print("your bmi is good")
    print("you are healthy, fit and fine")
    print("Write some halth blogs, create vlogs and share your secret of being healthy with others")
else:
    print("your bmi is high")

your bmi is  40.0
your bmi is high


In [105]:
w = int(input("Enter the weight in KG "))
h = int(input("Enter the height in CMs "))/100 
bmi = w/(h**2)
print("your bmi is ",bmi)

if bmi<25:
    print("your bmi is low")
    print("you need to eat more, walk less, get more healthy")
elif bmi>=25 and bmi<30:
    print("your bmi is good")
    print("you are healthy, fit and fine")
    print("Write some halth blogs, create vlogs and share your secret of being healthy with others")
else:
    print("your bmi is high")
    if bmi>45:
        print("you need to consult a dietian immediately")

your bmi is  45.91836734693878
your bmi is high
you need to consult a dietian immediately


#### Loops
    - used to repeat execution of a set of commands
    - for loop: to be used when we know exact count of repeatation
    - while loop: to be used when a condition based repeatation is to be done

In [3]:
print("Hello from python and ME")
print("Hello from python and ME")
print("Hello from python and ME")
print("Hello from python and ME")

Hello from python and ME
Hello from python and ME
Hello from python and ME
Hello from python and ME


In [4]:
for i in range(4):
    print("Hello from python  and ME")

Hello from python  and ME
Hello from python  and ME
Hello from python  and ME
Hello from python  and ME


In [6]:
password = ""
while password!="1212":
    password = input("Enter the correct password ")
    print("Try Again")
print("You are logged in ")

Try Again
Try Again
Try Again
Try Again


In [7]:
for i in range(4):
    print("Hello from python  and ME",i)

Hello from python  and ME 0
Hello from python  and ME 1
Hello from python  and ME 2
Hello from python  and ME 3


In [8]:
for i in range(2,19):
    print("hi from python ",i)

hi from python  2
hi from python  3
hi from python  4
hi from python  5
hi from python  6
hi from python  7
hi from python  8
hi from python  9
hi from python  10
hi from python  11
hi from python  12
hi from python  13
hi from python  14
hi from python  15
hi from python  16
hi from python  17
hi from python  18


In [9]:
for i in range(3,19,2):
    print("hi from python ",i)

hi from python  3
hi from python  5
hi from python  7
hi from python  9
hi from python  11
hi from python  13
hi from python  15
hi from python  17


In [11]:
x = ['London','Kualalumpur','HCM','Delhi','Bangalore']
for k in x:
    print(k)

London
Kualalumpur
HCM
Delhi
Bangalore


In [12]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [13]:
list(range(3,6))

[3, 4, 5]

In [14]:
list(range(2,9,3))

[2, 5, 8]

#### Guessing Game
- Write python code to create guessing game

    - create a variable ans = 5
    The game goes as below where user will get total 3 attempts to win the game
    - ask user to guess a number between 0 to 9
    - compare the user guess with ans, if equal then say "You won the jackpot"
    else say try again

    - make sure, user gets total of 3 attempts/chances to make a guess

    Hint : for loop + if else / while loop + if else

    #########################################

    Detailed Hint:
    
        create a variable ans = 5
        start with a for loop for 3 iterations
        ask user to make a guess and store it into a variable "guess", 
        convert guess to integer
        compare guess v/s ans, if equal
        say "you won the jackpot"
        else, say 'try again'


In [16]:
ans = 5
for i in range(3):
    guess = input("Guess a number between 0 to 9 ")
    guess = int(guess)
    if guess==ans:
        print("You won the jackpot")
    else:
        print('Try Again')


Try Again
Try Again
You won the jackpot


In [24]:
ans = 5
for i in range(5):
    guess = input("Guess a number between 0 to 9 ")
    guess = int(guess)
    if guess==ans:
        print("You won the jackpot")
        break
    else:
        if i==4:
            print("you Lost the game")
        else: 
            print('Try Again')


Try Again
Try Again
Try Again
Try Again
you Lost the game


In [23]:
for i in range(3):
    print(i)

0
1
2


In [25]:
ans = 5
while True:
    guess = input("Guess a number between 0 to 9 ")
    guess = int(guess)
    if guess==ans:
        print("You won the jackpot")
        break
    else:
        print('Try Again')

Try Again
Try Again
Try Again
Try Again
You won the jackpot


## Creating User Defined Functions

In [26]:
x= [4,5,3]
sorted(x)

[3, 4, 5]

In [39]:
sorted(x,reverse=True)

[5, 4, 3]

In [27]:
def myfunc():
    print("Hey good morning")
    print("hey hi, how are you doing")

In [28]:
myfunc()

Hey good morning
hey hi, how are you doing


In [29]:
myfunc()

Hey good morning
hey hi, how are you doing


In [30]:
def funcA(x,y):
    z = x + y
    return z

In [31]:
funcA(7,3)

10

In [32]:
funcA(7,5)

12

In [33]:
def funcA(x,y):
    z = x + y
    return z

In [34]:
k = funcA(7,6)
print(k)

13


In [35]:
def funcA(x,y):
    z = x + y
    print(z)

In [37]:
w = funcA(7,2)

9


In [38]:
print(w)

None


In [40]:
def get_bmi():
    w = int(input("Enter the weight in KG "))
    h = int(input("Enter the height in CMs "))/100 
    bmi = w/(h**2)
    print("your bmi is ",bmi)

    if bmi<25:
        print("your bmi is low")
        print("you need to eat more, walk less, get more healthy")
    elif bmi>=25 and bmi<30:
        print("your bmi is good")
        print("you are healthy, fit and fine")
        print("Write some halth blogs, create vlogs and share your secret of being healthy with others")
    else:
        print("your bmi is high")
        if bmi>45:
            print("you need to consult a dietian immediately")

In [41]:
get_bmi()

your bmi is  26.666666666666668
your bmi is good
you are healthy, fit and fine
Write some halth blogs, create vlogs and share your secret of being healthy with others


In [43]:

round(2.15648,2)

2.16

In [44]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [45]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [46]:
help(type)

Help on class type in module builtins:

class type(object)
 |  type(object_or_name, bases, dict)
 |  type(object) -> the object's type
 |  type(name, bases, dict) -> a new type
 |  
 |  Methods defined here:
 |  
 |  __call__(self, /, *args, **kwargs)
 |      Call self as a function.
 |  
 |  __delattr__(self, name, /)
 |      Implement delattr(self, name).
 |  
 |  __dir__(self, /)
 |      Specialized __dir__ implementation for types.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __instancecheck__(self, instance, /)
 |      Check if an object is an instance.
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  __setattr__(self, name, value, /)
 |      Implement setattr(self, name, value).
 |  
 |  __sizeof__(self, /)
 |      Return memory consumption of the type object.
 |  
 |  __subclasscheck__(self, subclass, /)
 |     

In [47]:
def funcA(x,y):
    """ DocString for the function
    This function can be used to add two numbers
    it expects two values
    x: int/float
    y: int/float
    returns
    z: int/float 
    """
    z = x + y
    print(z)

In [48]:
funcA(7,6)

13


In [49]:
help(funcA)

Help on function funcA in module __main__:

funcA(x, y)
    This function can be used to add two numbers
    it expects two values
    x: int/float
    y: int/float
    returns
    z: int/float



Exercise  1: Given a list, remove the element at index 4 and add it to the 2nd position and at the end of the list

list1 = [54, 44, 27, 79, 91, 41]

In [54]:
def changepos(x):
    "this function is to change position"
    val = x.pop(4)
    x.insert(2,val)
    x.append(val)
    return x

x = [54, 44, 27, 79, 91, 41]
changepos(x)


[54, 44, 91, 27, 79, 41, 91]

Exercise 2: Remove duplicate from a list and create a tuple and find the minimum and maximum number

sampleList = [87, 45, 41, 65, 94, 41, 99, 94]

In [51]:
sampleList = [87, 45, 41, 65, 94, 41, 99, 94]
myset = set(sampleList)
mytuple = tuple(myset)
print(min(mytuple),max(mytuple))

41 99


In [ ]:
def funcB(y):
    m = set(y)
    d = tuple(m)
    return min(d),max(d)

In [53]:
help(min)

Help on built-in function min in module builtins:

min(...)
    min(iterable, *[, default=obj, key=func]) -> value
    min(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its smallest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the smallest argument.



In [55]:
import sept as sp

In [56]:
sp.greet()

hey good morning


In [57]:
sp.mult(7,5)

35

In [58]:
sp.myfun(4,2)

6

### OS: operating system

In [60]:
import os

In [61]:
os.getcwd() # fetch the current directory where files are saved

'd:\\AI\\Python-Programming\\HereTech'

In [72]:
# create a new folder
os.mkdir("D:\AI\Day1Codes")

In [64]:
# get the list of files and folder in any directory
os.listdir('d:\\AI\\Python-Programming\\HereTech')

['code1_python_fundamentails.ipynb', 'Day1Codes', 'sept.py', '__pycache__']

In [65]:
# check if the folder exists
os.path.isdir("Day1Codes")

True

In [67]:
os.cpu_count() # number of cores in the processor

8

In [73]:
# create a new folder
os.mkdir("myfolder")

In [74]:
os.rmdir("myfolder")

In [75]:
help(os)

Help on module os:

NAME
    os - OS routines for NT or Posix depending on what system we're on.

MODULE REFERENCE
    https://docs.python.org/3.9/library/os
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This exports:
      - all functions from posix or nt, e.g. unlink, stat, etc.
      - os.path is either posixpath or ntpath
      - os.name is either 'posix' or 'nt'
      - os.curdir is a string representing the current directory (always '.')
      - os.pardir is a string representing the parent directory (always '..')
      - os.sep is the (or a most common) pathname separator ('/' or '\\')
      - os.extsep is the extension separator (always '.')
      - os.altsep is the alternate pathname se

#### math: mathematical operations

In [68]:
import math

In [69]:
math.sin(math.radians(90))

1.0

In [70]:
math.sqrt(625)

25.0

In [71]:
math.log10(10000)

4.0

## Working with numpy

In [12]:
import numpy as np

In [3]:
a = [7,5,2]
b = [9,6,2]
print(a+b)

[7, 5, 2, 9, 6, 2]


In [13]:
a = np.array([4,2,6])
b = np.array([7,4,2])
print(a+b)

[11  6  8]


In [5]:
a = np.array([ [7,54,2],
               [8,12,41],
               [9,5,2]])
print(a)

[[ 7 54  2]
 [ 8 12 41]
 [ 9  5  2]]


In [6]:
type(a)

numpy.ndarray

In [7]:
a.shape

(3, 3)

In [8]:
a.min()

2

In [9]:
a.max()

54

In [10]:
a.mean()

15.555555555555555

In [11]:
print(np.sin(np.deg2rad(90)))
print(np.log10(5222))
print(np.exp(72.5))
print(np.square(12))

1.0
3.7178368674869255
3.0644316416992722e+31
144


## 21st September: more with numpy

In [14]:
import numpy as np

In [16]:
# generating arrays with numpy
x = np.arange(start=5, stop=20,step=1.5)
x

array([ 5. ,  6.5,  8. ,  9.5, 11. , 12.5, 14. , 15.5, 17. , 18.5])

In [17]:
x = np.zeros((2,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
x = np.ones((2,3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
m = 5*np.ones((3,5))
m

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [20]:
# generating random numbers: uniform distribution between 0 to 1
x = np.random.rand(10)
x

array([0.10171332, 0.78206042, 0.52679386, 0.13243852, 0.44840067,
       0.24282576, 0.79589133, 0.21043765, 0.66311851, 0.12963416])

In [21]:
# generating random values with normal distribuition, mean ~ 0, std ~1
x = np.random.randn(20)
x

array([ 2.50142834e+00, -1.01054812e+00, -9.78283603e-01, -5.03811471e-01,
        4.98977026e-01,  2.39803549e-03, -4.59357397e-01, -1.84213874e+00,
       -1.90594732e+00,  2.11428461e+00, -1.31494598e+00,  1.48323037e-01,
       -1.76204647e+00,  6.55728988e-01, -2.16636588e-01,  3.42499692e-01,
        1.07964362e+00, -9.39918653e-02,  6.97641007e-01, -2.00308309e-01])

In [22]:
# generating integer random numbers
x = np.random.randint(4,100,3)
x

array([83, 57, 10])

#### Linear Algebra with numpy

In [23]:
a = np.array([ [7,54,2],
               [8,12,41],
               [9,5,2]])
print(a)

[[ 7 54  2]
 [ 8 12 41]
 [ 9  5  2]]


In [24]:
# determinant of matrix
np.linalg.det(a)

17659.000000000004

In [25]:
# inverse of matrix
np.linalg.inv(a)

array([[-0.01024973, -0.00554958,  0.12401608],
       [ 0.01998981, -0.00022651, -0.01534628],
       [-0.00385073,  0.02553939, -0.01970667]])

In [26]:
# eigen values & eigen vectors
np.linalg.eig(a)

(array([ 42.96879516 +0.j       , -10.98439758+17.0386522j,
        -10.98439758-17.0386522j]),
 array([[-0.81143151+0.j        ,  0.86437652+0.j        ,
          0.86437652-0.j        ],
        [-0.53148104+0.j        , -0.28315276+0.28297071j,
         -0.28315276-0.28297071j],
        [-0.24311891+0.j        , -0.12752088-0.27630373j,
         -0.12752088+0.27630373j]]))

    5x - 2y = 17
    3x + y = 19

In [27]:
# solving pair of linear equations
# create a list of coeffificents
a = [[5,-2], [3,1]]
# list of constants
b = [17,19]

np.linalg.solve(a,b)

array([5., 4.])